---
# Job template - to be used in a pipeline by including this file.
# Make sure to include the .validate stage in the pipeline template
#
# Lints a Dockerfile
#
# include:
#  - .gitlab/dockerfile-lint.gitlab-ci.yml

lint_dockerfile:
  extends: .sast
  dependencies: []
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  image:
    name: hadolint/hadolint:v2.10.0-debian
  script:
    - mkdir -p reports || true
    - hadolint Dockerfile | tee reports/hadolint-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/hadolint-report.txt
